export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const SCROLL_ACTIVITIES_FETCH = "SCROLL_ACTIVITIES_FETCH";
export const SCROLL_ACTIVITIES_SUCCESS = "SCROLL_ACTIVITIES_SUCCESS";
export const SCROLL_ACTIVITIES_FAILURE = "SCROLL_ACTIVITIES_FAILURE";
export const SELECT_ACTIVITY = "SELECT_ACTIVITY";
export const SWIPE_ACTIVITY_INFO = "SWIPE_ACTIVITY_INFO";
