export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const SCROLL_ACTIVITIES = "SCROLL_ACTIVITIES";
export const SELECT_ACTIVITY = "SELECT_ACTIVITY";
export const SWIPE_ACTIVITY_INFO = "SWIPE_ACTIVITY_INFO";
