module.exports = {
  data: [
    {
      firstName: "Junjie",
      lastName: "Jiang",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Eric",
      lastName: "Abenojar",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Julian",
      lastName: "Mazaira",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Moose",
      lastName: "Doose",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Irvin",
      lastName: "Tang",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Andrew",
      lastName: "",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Irvin",
      lastName: "Tang",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
    {
      firstName: "Irvin",
      lastName: "Tang",
      profileImg: "",
      description: "",
      hobbies: [],
      images: [],
      video: "",
      connections: [],
    },
  ]
};
